# Generated by Django 3.1.2 on 2020-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude of the sighting')),
                ('longitude', models.FloatField(help_text='Longitude of the sighting')),
                ('unique_squirrel_id', models.CharField(help_text='The unique id of squirrel(Format:Hectare-Shift-Date-Hectare Squirrel Number)', max_length=20, unique=True)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Shift', max_length=5)),
                ('date', models.DateField(help_text='Format:mmddyyyy')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], help_text='Age of squirrel', max_length=10)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray')], help_text='Primary Fur Color', max_length=10)),
                ('location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plance')], help_text='Location of squirrel', max_length=20)),
                ('specific_location', models.TextField(blank=True, help_text='Specific Location')),
                ('running', models.BooleanField(help_text='Whether or not the squirrel is running')),
                ('chasing', models.BooleanField(help_text='Whether or not the squirrel is chasing')),
                ('climbing', models.BooleanField(help_text='Whether or not the squirrel is climbing')),
                ('eating', models.BooleanField(help_text='Whether or not the squirrel is eating')),
                ('foraging', models.BooleanField(help_text='Whether or not the squirrel is foraging')),
                ('other_activities', models.TextField(blank=True, help_text='Other activities the squirrel is doing')),
                ('kuks', models.BooleanField(help_text='Whether or not the squirrel kuks')),
                ('quaas', models.BooleanField(help_text='Whether or not the squirrel quaas')),
                ('moans', models.BooleanField(help_text='Whether or not the squirrel moans')),
                ('tail_flags', models.BooleanField(help_text='Whether or not its tail flags')),
                ('tail_twitches', models.BooleanField(help_text='Whether or not its tail twitches')),
                ('approaches', models.BooleanField(help_text='Whether or not the squirrel approaches')),
                ('indifferent', models.BooleanField(help_text='Whether or not the squirrel is indifferent')),
                ('runs_from', models.BooleanField(help_text='Whether or not the squirrel runs from you')),
            ],
        ),
    ]
